apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: us-west1-docker.pkg.dev/elated-bus-460108-d0/devops-repo-akw/devops-app:v1
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "PROD"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"